### ISSUE TITLE
Website link on Chrome Store broken

### ISSUE THREAD

**Issue by matt-richardson** [davidroberts63/OctoPygmy#22]
On the [Blue fin](https://chrome.google.com/webstore/detail/blue-fin/gmnfhfdbcadjmpoigffmoondjhblabom?hl=en-US&gl=US) page on the chrome web store, the website link points to http://blufin.teapotcoder.com/ rather than http://bluefin.teapotcoder.com/ ("blue" is missing an "e")

**Comment by davidroberts63** [comment]
Thank you. Just fixed it.
