### ISSUE TITLE
Can't filter dashboard if there's a project group name that starts with a number

### ISSUE THREAD

**Issue by micdenny** [davidroberts63/OctoPygmy#28]
Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '[octopygmy-id=1services-grouping]' is not a valid selector.

![image](https://cloud.githubusercontent.com/assets/1633595/12461373/d1b168dc-bfb8-11e5-92e9-045fc2aa9520.png)

I use the number to order the dashboard project groups, is there another way to do it? :smile: 

To now I've worked around this adding a letter in front of the number.

**Comment by davidroberts63** [comment]
Ah, yeah. I can take care of that. Thanks for bringing it up. No workaround right now though.

I know HTML5 is more permissive on things like that but I've always wondered what we developers have against things starting with a number.

**Comment by micdenny** [comment]
at the moment I've added a letter before the number ;) before I had `1 Services`, now I have `P1 Services` and it works, but of course if you can fix it it would be better :smile:

**Comment by micdenny** [comment]
Thank you!
