### ISSUE TITLE
Filter machines by state doesn't work for offline or disabled

### ISSUE THREAD

**Issue by matt-richardson** [davidroberts63/OctoPygmy#42]
Just found a few oddities with the "filter machines by state" functionality - it only appears to work for online machines.

If you search for 'disabled', it shows disabled machines, offline machines, and online machines that need a calamari upgrade (only hides online machines).

If you search for 'offline', it shows all machines.

It appears that [here](https://github.com/davidroberts63/OctoPygmy/blob/master/src/3.0/environment-filter.js#L25) and [here](https://github.com/davidroberts63/OctoPygmy/blob/master/src/3.0/environment-filter.js#L27) are both missing a `>= 0` check.

Probably need another state for "CalamariNeedsUpgrade" as well.

Also had a thought that this functionality is not very discoverable... Maybe a tooltip or some placeholder text might be useful?

**Comment by davidroberts63** [comment]
Good point on it not being very discoverable. In fact I completely forgot about it!

Interesting what you are seeing. I need to check it against my 3.X install later tonight. We are still on 2.x at work (in the process of upgrading at the moment).

Yes I agree the problem would be at those two spots. I'll be sending out an update tonight 'Octo Version Analytics' so I'll include that fix. Would you like to verify it on your end first? Adding the 'Calimari needs upgrade' state filter as well?

**Comment by matt-richardson** [comment]
I've just had a quick play:

Updating the `determineStatus` at [environment-filter.js#L21](https://github.com/davidroberts63/OctoPygmy/blob/master/src/3.0/environment-filter.js#L21) to
```
	function determineStatus(node)
	{
		if (node.src.indexOf("Server-Online") >= 0) {
			return "online";
		} else if (node.src.indexOf("Server-Disabled") >= 0) {
			return "disabled";
		} else if (node.src.indexOf("Server-Offline") >= 0) {
			return "offline";
		}
	}
```

Works well. It still leaves the "Update calamari on this/these machines" button visible, but with this fix it works better than it did.

Would like to do a PR, but dont have time today, unfortunately.

**Comment by davidroberts63** [comment]
I'll add it to my analytics pr tonight.
