### ISSUE TITLE
Update Step Template not working for certain number of usages

### ISSUE THREAD

**Issue by davidroberts63** [davidroberts63/OctoPygmy#44]
Originally posted by @davidmoney on 3/16/2016 at 10:00am

Hi, I am just trying out bluefin and was wondering if there Is an issue with the update all  button in step templates in octo v3.3.1 or is there something i am missing?
When you click on it nothing happens.  The step is being used 34 times.
Cheers

update: i manually tried updating several then tried the update all again and it worked. 
Is there a maximum usage for the update all to work on?

**Comment by davidroberts63** [comment]
This is the second time I've heard someone mentioning that the Update Step Template usage only working for a certain number of usages. 25 to be specific in the last mention. I'll try to take a look at this soon.

**Comment by George-CAPHPI** [comment]
I have experienced this before, but it is very much to do with the type of change that has been applied to the step template. Some changes _have_ to be done manually. I believe that this is occurs when you change the signature of the step, not just the step template code.

**Comment by davidroberts63** [comment]
That's correct. If the parameters of the step template have changed Bluefin cannot accurately determine what to do so it does nothing. But it should continue to do the other steps if it can. I still need to look into it.

**Comment by davidroberts63** [comment]
Figured this one out. The original release of Update All template usage did not take into account child steps.

**Comment by davidroberts63** [comment]
Fixed in 1.5.4
bd5f26bafc07344498d7999e378396a9d0a29e37
